export const LOAD_STATUS_PENDING = "LOAD_STATUS_PENDING";
export const LOAD_STATUS_FULFILLED = "LOAD_STATUS_FULFILLED";
export const LOAD_STATUS_REJECTED = "LOAD_STATUS_REJECTED";

export const LOAD_TYPE_PENDING = "LOAD_TYPE_PENDING";
export const LOAD_TYPE_FULFILLED = "LOAD_TYPE_FULFILLED";
export const LOAD_TYPE_REJECTED = "LOAD_TYPE_REJECTED";

export const LOAD_TAGS_PENDING = "LOAD_TAGS_PENDING";
export const LOAD_TAGS_FULFILLED = "LOAD_TAGS_FULFILLED";
export const LOAD_TAGS_REJECTED = "LOAD_TAGS_REJECTED";

export const LOAD_CURRENCY_PENDING = "LOAD_CURRENCY_PENDING";
export const LOAD_CURRENCY_FULFILLED = "LOAD_CURRENCY_FULFILLED";
export const LOAD_CURRENCY_REJECTED = "LOAD_CURRENCY_REJECTED";
